# Generated by Django 5.0.3 on 2024-03-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('title',), 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
    ]
